# Generated by Django 5.0 on 2026-05-15 23:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StemJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('source_audio_url', models.TextField()),
                ('source_filename', models.CharField(max_length=255)),
                ('source_file_size_bytes', models.BigIntegerField()),
                ('model_used', models.CharField(default='demucs-v4', max_length=40)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('progress_pct', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('credits_used', models.IntegerField(default=2)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stem_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StemFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stem_type', models.CharField(choices=[('vocals', 'Vocals'), ('no_vocals', 'No Vocals (Karaoke)'), ('bass', 'Bass'), ('drums', 'Drums'), ('other', 'Other')], max_length=20)),
                ('audio_s3_key', models.TextField()),
                ('duration_seconds', models.IntegerField(blank=True, null=True)),
                ('file_size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stem_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stem_files', to='stems.stemjob')),
            ],
        ),
    ]
