# Generated by Django 5.0 on 2026-05-12 23:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarjeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_payment_method_id', models.CharField(max_length=255)),
                ('stripe_customer_id', models.CharField(max_length=255)),
                ('brand', models.CharField(max_length=50)),
                ('last4', models.IntegerField()),
                ('exp_month', models.IntegerField()),
                ('exp_year', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarjetas', to='user.usuario')),
            ],
            options={
                'db_table': 'tarjetas',
            },
        ),
    ]
