# Generated by Django 5.0 on 2026-05-13 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tarjeta',
            old_name='created_at',
            new_name='createdAt',
        ),
        migrations.RenameField(
            model_name='tarjeta',
            old_name='exp_month',
            new_name='expMonth',
        ),
        migrations.RenameField(
            model_name='tarjeta',
            old_name='exp_year',
            new_name='expYear',
        ),
        migrations.RenameField(
            model_name='tarjeta',
            old_name='stripe_customer_id',
            new_name='stripeCustomerId',
        ),
        migrations.RenameField(
            model_name='tarjeta',
            old_name='stripe_payment_method_id',
            new_name='stripePaymentMethodId',
        ),
    ]
