# Generated by Django 5.0 on 2026-05-13 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rol',
            old_name='created_at',
            new_name='createdAt',
        ),
        migrations.RenameField(
            model_name='rol',
            old_name='es_system',
            new_name='esSystem',
        ),
        migrations.RenameField(
            model_name='rol',
            old_name='updated_at',
            new_name='updatedAt',
        ),
    ]
