# Generated by Django 5.0 on 2026-05-13 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0002_rename_created_at_rol_createdat_and_more'),
        ('role', '0002_seed_roles'),
    ]

    operations = [
    ]
