# Generated by Django 5.0 on 2026-05-13 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('role_permission', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rolpermiso',
            old_name='assigned_at',
            new_name='assignedAt',
        ),
    ]
