# apps/songs/models.py
from apps.core.models import BaseModel
from django.db import models
from django.conf import settings


class Tag(models.Model):
    """Categorías/géneros de canciones. Ej: reggaeton, lofi, sad."""
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=60, unique=True)
    category = models.CharField(
        max_length=40,
        choices=[('genre', 'Genre'), ('mood', 'Mood'), ('tempo', 'Tempo')],
        default='genre'
    )
    emoji = models.CharField(max_length=10, null=True, blank=True)

    def __str__(self):
        return self.name


class Song(BaseModel):
    """
    Una canción generada por el sistema.
    status: draft → queued → processing → ready | failed | no_credits
    """
    STATUS_CHOICES = [
        ('draft', 'Draft'),
        ('queued', 'Queued'),
        ('processing', 'Processing'),
        ('ready', 'Ready'),
        ('failed', 'Failed'),
        ('no_credits', 'No Credits'),
    ]
    LYRICS_SOURCE_CHOICES = [
        ('user', 'Written by user'),
        ('ai_generated', 'Generated by AI'),
        ('described', 'Described to AI'),
    ]

    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name='songs'
    )
    title = models.CharField(max_length=200)
    description = models.TextField(null=True, blank=True)   # full_described_song
    prompt = models.TextField(null=True, blank=True)         # tags de estilo
    lyrics = models.TextField(null=True, blank=True)
    described_lyrics = models.TextField(null=True, blank=True)
    lyrics_source = models.CharField(
        max_length=20, choices=LYRICS_SOURCE_CHOICES, default='user'
    )
    lyrics_timestamps = models.JSONField(null=True, blank=True)
    instrumental = models.BooleanField(default=False)
    vocal_type = models.CharField(
        max_length=10,
        choices=[('male', 'Male'), ('female', 'Female'), ('auto', 'Auto')],
        default='auto',
    )
    language = models.CharField(
        max_length=10,
        choices=[('es', 'Spanish'), ('en', 'English')],
        default='es',
    )

    # Parámetros de generación (del ZIP)
    guidance_scale = models.FloatField(default=10.0)
    infer_step = models.IntegerField(default=100)
    audio_duration = models.FloatField(default=180.0)
    seed = models.IntegerField(default=-1)

    # Resultado
    audio_s3_key = models.TextField(null=True, blank=True)
    thumbnail_s3_key = models.TextField(null=True, blank=True)
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='draft')

    # Comunidad
    is_public = models.BooleanField(default=False)
    play_count = models.IntegerField(default=0)
    like_count = models.IntegerField(default=0)

    # Relaciones
    tags = models.ManyToManyField(Tag, through='SongTag', blank=True)

    class Meta:
        ordering = ['-created_at']
        indexes = [
            models.Index(fields=['user', 'status']),
            models.Index(fields=['is_public', 'created_at']),
        ]

    def __str__(self):
        return f"{self.title} ({self.status})"

    @property
    def is_ready(self):
        return self.status == 'ready'


class SongTag(models.Model):
    song = models.ForeignKey(Song, on_delete=models.CASCADE)
    tag = models.ForeignKey(Tag, on_delete=models.CASCADE)

    class Meta:
        unique_together = [('song', 'tag')]


class GenerationJob(BaseModel):
    """
    Registro de cada intento de generación.
    Permite auditar fallas, reintentos y consumo de créditos.
    """
    MODE_CHOICES = [
        ('from_description', 'From full description'),
        ('with_lyrics', 'Custom prompt + lyrics'),
        ('with_described_lyrics', 'Custom prompt + described lyrics'),
    ]

    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name='generation_jobs'
    )
    song = models.OneToOneField(
        Song, on_delete=models.CASCADE,
        related_name='generation_job',
        null=True, blank=True
    )
    mode = models.CharField(max_length=30, choices=MODE_CHOICES)
    modal_endpoint_used = models.CharField(max_length=200, blank=True)
    status = models.CharField(
        max_length=20,
        choices=[('queued','Queued'),('processing','Processing'),
                 ('completed','Completed'),('failed','Failed'),('no_credits','No Credits')],
        default='queued'
    )
    error_message = models.TextField(null=True, blank=True)
    credits_used = models.IntegerField(default=0)
    started_at = models.DateTimeField(null=True, blank=True)
    completed_at = models.DateTimeField(null=True, blank=True)