# Generated by Django 5.0 on 2026-05-13 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='created_at',
            new_name='createdAt',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='foto_base64',
            new_name='fotoBase64',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='nombre_completo',
            new_name='nombreCompleto',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='password_hash',
            new_name='passwordHash',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='stripe_customer_id',
            new_name='stripeCustomerId',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='updated_at',
            new_name='updatedAt',
        ),
    ]
