# Generated by Django 5.0 on 2026-05-19 03:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60, unique=True)),
                ('category', models.CharField(choices=[('genre', 'Genre'), ('mood', 'Mood'), ('tempo', 'Tempo')], default='genre', max_length=40)),
                ('emoji', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('prompt', models.TextField(blank=True, null=True)),
                ('lyrics', models.TextField(blank=True, null=True)),
                ('described_lyrics', models.TextField(blank=True, null=True)),
                ('lyrics_source', models.CharField(choices=[('user', 'Written by user'), ('ai_generated', 'Generated by AI'), ('described', 'Described to AI')], default='user', max_length=20)),
                ('instrumental', models.BooleanField(default=False)),
                ('guidance_scale', models.FloatField(default=15.0)),
                ('infer_step', models.IntegerField(default=60)),
                ('audio_duration', models.FloatField(default=180.0)),
                ('seed', models.IntegerField(default=-1)),
                ('audio_s3_key', models.TextField(blank=True, null=True)),
                ('thumbnail_s3_key', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('queued', 'Queued'), ('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed'), ('no_credits', 'No Credits')], default='draft', max_length=20)),
                ('is_public', models.BooleanField(default=False)),
                ('play_count', models.IntegerField(default=0)),
                ('like_count', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GenerationJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('mode', models.CharField(choices=[('from_description', 'From full description'), ('with_lyrics', 'Custom prompt + lyrics'), ('with_described_lyrics', 'Custom prompt + described lyrics')], max_length=30)),
                ('modal_endpoint_used', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('no_credits', 'No Credits')], default='queued', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('credits_used', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generation_jobs', to=settings.AUTH_USER_MODEL)),
                ('song', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='generation_job', to='songs.song')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SongTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='songs.song')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='songs.tag')),
            ],
            options={
                'unique_together': {('song', 'tag')},
            },
        ),
        migrations.AddField(
            model_name='song',
            name='tags',
            field=models.ManyToManyField(blank=True, through='songs.SongTag', to='songs.tag'),
        ),
        migrations.AddIndex(
            model_name='song',
            index=models.Index(fields=['user', 'status'], name='songs_song_user_id_9d7f51_idx'),
        ),
        migrations.AddIndex(
            model_name='song',
            index=models.Index(fields=['is_public', 'created_at'], name='songs_song_is_publ_d2b8a5_idx'),
        ),
    ]
