# Generated by Django 5.0 on 2026-06-20 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("songs", "0005_song_lyrics_timestamps"),
        ("songs", "0006_remove_song_ml_fields"),
    ]

    operations = []
