# Generated by Django 5.0 on 2026-06-22 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mix', '0001_initial'),
        ('songs', '0007_merge_20260620_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='mixproject',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='mix_projects', to='songs.tag'),
        ),
    ]
