# Generated by Django 5.0 on 2026-06-21 22:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('songs', '0007_merge_20260620_1027'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KaraokeTrack',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('instrumental_s3_key', models.TextField(blank=True, null=True)),
                ('vocals_s3_key', models.TextField(blank=True, null=True)),
                ('lyrics', models.TextField(blank=True, null=True)),
                ('lyrics_timestamps', models.JSONField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('song', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='karaoke_track', to='songs.song')),
            ],
        ),
        migrations.CreateModel(
            name='UserKaraokeAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credits_paid', models.IntegerField(default=2)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('karaoke_track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_accesses', to='karaoke.karaoketrack')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='karaoke_accesses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='karaoketrack',
            index=models.Index(fields=['status'], name='karaoke_kar_status_0f0863_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userkaraokeaccess',
            unique_together={('user', 'karaoke_track')},
        ),
    ]
