# Generated by Django 5.0 on 2026-05-12 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('precio', models.FloatField(default=0)),
                ('credito_por_mes', models.IntegerField(default=0)),
                ('credito_ilimitado', models.BooleanField(default=False)),
                ('stripe_price_id', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'planes',
            },
        ),
    ]
