# Generated by Django 5.0 on 2026-05-13 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plan',
            old_name='credito_ilimitado',
            new_name='creditoIlimitado',
        ),
        migrations.RenameField(
            model_name='plan',
            old_name='credito_por_mes',
            new_name='creditoPorMes',
        ),
        migrations.RenameField(
            model_name='plan',
            old_name='stripe_price_id',
            new_name='stripePriceId',
        ),
    ]
