# Generated by Django 5.0 on 2026-05-13 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pago',
            old_name='created_at',
            new_name='createdAt',
        ),
        migrations.RenameField(
            model_name='pago',
            old_name='stripe_payment_intent_id',
            new_name='stripePaymentIntentId',
        ),
    ]
