# Generated by Django 5.0 on 2026-05-13 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='suscripcion',
            old_name='created_at',
            new_name='createdAt',
        ),
        migrations.RenameField(
            model_name='suscripcion',
            old_name='current_period_end',
            new_name='currentPeriodEnd',
        ),
        migrations.RenameField(
            model_name='suscripcion',
            old_name='current_period_start',
            new_name='currentPeriodStart',
        ),
        migrations.RenameField(
            model_name='suscripcion',
            old_name='stripe_subscription_id',
            new_name='stripeSubscriptionId',
        ),
    ]
